<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403075519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE breathing_exercises (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, slug VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, inspiration_duration INT NOT NULL, apnea_duration INT NOT NULL, expiration_duration INT NOT NULL, cycles INT NOT NULL, is_preset BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA174FCC989D9B62 ON breathing_exercises (slug)');
        $this->addSql('CREATE TABLE user_sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, breathing_exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7AED7913A76ED395 ON user_sessions (user_id)');
        $this->addSql('CREATE INDEX IDX_7AED7913F42A680 ON user_sessions (breathing_exercise_id)');
        $this->addSql('ALTER TABLE user_sessions ADD CONSTRAINT FK_7AED7913A76ED395 FOREIGN KEY (user_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_sessions ADD CONSTRAINT FK_7AED7913F42A680 FOREIGN KEY (breathing_exercise_id) REFERENCES breathing_exercises (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_sessions DROP CONSTRAINT FK_7AED7913A76ED395');
        $this->addSql('ALTER TABLE user_sessions DROP CONSTRAINT FK_7AED7913F42A680');
        $this->addSql('DROP TABLE breathing_exercises');
        $this->addSql('DROP TABLE user_sessions');
    }
}
